stages:
  - docker-pkg
  - k8s-deploy


variables:
  PROJECT_NAME: hyperf 
  REGISTRY_URL: fp-harbor.fitipower.inc/hyperf/hyperf

docker-pkg:
  stage: docker-pkg
  before_script:
    - docker login -u ocean.hsu -p Vm6ru8123  fp-harbor.fitipower.inc
  script:
    - docker build  -t  $REGISTRY_URL  .
    - docker push   $REGISTRY_URL 
  allow_failure: false

k8s-deploy:
  stage: k8s-deploy
  script:
    - kubectl apply -f ./hyperf.yaml
  allow_failure: false
  dependencies:
    - docker-pkg


