stages:
  - docker-pkg
#  - Ai-Stack-Test
  #- k8s-deploy


#variables:
  #PROJECT_NAME: hyperf 
  #REGISTRY_URL: fp-harbor.fitipower.inc/hyperf/hyperf
 # PROJECT_NAME: iss
 # REGISTRY_URL: 10.1.11.45:18080/iss/test
docker-pkg:
  stage: docker-pkg
  #before_script:
    #- docker login -u ocean.hsu -p Vm6ru8123  fp-harbor.fitipower.inc
    #- docker login -u admin -p harbor@iss 10.1.11.45:18080
   
  script:
    - ./etc/gitlab-runner/script/yoyo5.sh
  #  - docker build  -t  $REGISTRY_URL  .
  #  - docker push   $REGISTRY_URL 
  allow_failure: false

#Ai-Stack-Test-GPU:
#  stage: Ai-Stack-Test
#  script:
#    - kubectl apply -f ./test_cpu.yaml
#  allow_failure: false

#Ai-Stack-Test-SVC:
#  stage: Ai-Stack-Test
#  script:
#    - kubectl apply -f ./test_svc.yaml
#  allow_failure: false
#k8s-deploy:
  #stage: k8s-deploy
  #script:
    #- kubectl apply -f ./hyperf.yaml
  #allow_failure: false
  #dependencies:
    #- docker-pkg

