stages:
  - docker-pkg
  - k8s-deploy
  - delete-k8s-deploy

variables:
  PROJECT_NAME: hyperf 
  REGISTRY_URL: k8s-harbor.fitipower.inc/hyperf/hyperf

docker-pkg:
  stage: docker-pkg
  before_script:
    - docker login -u admin -p Harbor12345  k8s-harbor.fitipower.inc
  script:
    - docker build  -t  $REGISTRY_URL  .
    - docker push   $REGISTRY_URL 
  allow_failure: false

k8s-deploy:
  stage: k8s-deploy
  script:
    - kubectl apply -f ./hyperf.yaml
  allow_failure: false
  dependencies:
    - docker-pkg

delete-deploy:
  stage: delete-k8s-deploy
  script: kubectl delete deploy transport
  allow_failure: false

delete-svc:
  stage: delete-k8s-deploy
  script: kubectl delete svc transport
  allow_failure: false

