apiVersion: v1
kind: Service
metadata:
  name: gpuservice
spec:
  type: NodePort
  ports:
  - name: ssh
    nodePort: 32000
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: binpack-1
