apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-deploy
spec:
  replicas: 1
  strategy:
        type: RollingUpdate
                rollingUpdate:
                   maxSurge: 25%
                   maxUnavailable: 25%  
  template:
        metadata:
           labels:
             app: 
        spec:
          containers:
            - name: test-deploy
              image: 10.1.11.45:18080/library/ultralytics/yolov5:v1
                          imagePullPolicy: IfNotPresent
