apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
spec:
  replicas: 1
  strategy:
        rollingUpdate:
                   maxSurge: 25%
                   maxUnavailable: 25%  
        type: RollingUpdate
  template:
        metadata:
           labels:
             app: test-deploy 
        spec:
          containers:
            - name: test-deploy
              image: 10.1.11.45:18080/library/ultralytics/yolov5:v1
              imagePullPolicy: IfNotPresent
