apiVersion: apps/v1
kind: Deployment

metadata:
  name: binpack-1
  labels:
    app: binpack-1

spec:
  replicas: 1
  selector: # define how the deployment finds the pods it manages
    matchLabels:
      app: binpack-1
  template: # define the pods specifications
    metadata:
      labels:
        app: binpack-1
    spec:
      containers:
      - name: binpack-1
        image: 10.1.11.45:18080/library/ultralytics/yolov5:v1
        resources:
          limits:
            aliyun.com/gpu-mem: "2"
            cpu: "4"
            memory: 8Gi
          requests:
            aliyun.com/gpu-mem: "2"
            cpu: "4"
            memory: 8Gi
      nodeSelector:
        iss_gpumemory: "20"
        iss_gputype: GRIDA100D-20C
